language: android
dist: trusty

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.0

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-x86-android-26
#    - sys-img-armeabi-v7a-android-17

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: buildPullRequest
      if: (type IN (pull_request))
      before_install:
        - mkdir "$ANDROID_HOME/licenses" || true
        - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
      script:
        - ./gradlew clean :security:assembleDebug --stacktrace
        - ./gradlew :security:testDebugUnitTest --info
        - ./gradlew lint --stacktrace
        - ./gradlew :security:testDebugUnitTestCoverage
      after_success:
        - ./gradlew :security:testReleaseUnitTestCoverage :security:copyJacocoReport coveralls --info
    - stage: buildDefault
      if: (type IN (push))
      before_install:
        - mkdir "$ANDROID_HOME/licenses" || true
        - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
      script:
        - ./gradlew clean :security:assemble --stacktrace
        - ./gradlew :security:testReleaseUnitTest --info
      after_success:
        - ./gradlew :security:testReleaseUnitTestCoverage :security:copyJacocoReport coveralls --info
#      deploy:
#        - provider: script
#          script: ./gradlew install bintrayUpload --info
#          skip_cleanup: true
#          on:
#            branch: master
#            tags: true
#        - provider: releases
#          api_key:
#            secure: "lwb8DJFAgSZzlrQ+NjsLSQqMju9vt/k63DQ24GW5lPTi5ZUcharrf+VexZmnxkYlIrrfYCpimqXw6GeSpi3hsys5pTT+0J53FjGvraT8g4X21teLhWlVLBeh5pIVw3VGWOcut/nJRcD4POnXTJV6kK/78qvUpddzrqYz72S9jGRt0kxDCxjYfcYBcx1OiFogy++nA9CTkMJkUsFC3asWwBSiZK2rc3TG5NIdrrlT6F0fOWELYxc1HT3W2P1tGi2f/V4G0XRop2Qe+zWNdlggkkQzw2slKrWbmf+nPK/TMCJLgXw2Uaru+P/SHW3Amg+thAibSJQFPQ1oJmUU7MuuCBAeu+Wyv//S35BjKhmQ94C0e8bSCJajGzR6/LjtOGVsAaJWLhq0F5k7v/UeGFb8fYDFDlbelzcQf2Df0ujBagDIadFzf+MQFnoG/B94lkPA/PSa9DFqZEPf4z1uTIRL0HL5ALFxRxpCyKaydmBvV4I9hHFZ2but1Pzx07ziP0JbQK7U1XdmPUHSePe/iLKz1NaXSwAChtwqsKTzww7vOCdlgjlU4x7uphu7HWk1m35hxBR5l7wPSp+jSw7gsmXmQlqPBJeNgGzGfBmH849dcV+PeVwYHiDsNzyqaeNCEir8UQBEe2ufTB+Irt+QvNswb35VHwXz2IhcrhRUzRdEs8Y="
#          file_glob: true
#          file:
#            - 'armadillo/build/outputs/aar/*.aar'
#          skip_cleanup: true
#          on:
#            branch: master
#            tags: true